#!/bin/bash

echo enter two numbers
read n1 n2
remainder=1
# Сохраняй номера для использования в будущем
t1=$n1
t2=$n2
if [ $n2 -eq 0 ]
then
echo "GCD of $n1 and $n2 = $n1"
exit 0
fi
while [ $remainder -ne 0 ]
do
remainder=`expr $n1 % $n2`

n1=$n2
n2=$remainder
done
echo "GCD of $t1 , $t2 is $n1"
