#!/bin/bash

echo Enter two number:
read m n
temp=`expr $m \* $n`
while [ $m != $n ]
do
    if [ $m -gt $n ]
    then
            m=`expr $m - $n`
    else
            n=`expr $n - $m`
    fi
done
echo gcd=$n
lcm=`expr $temp / $n`

echo The LCM is: $lcm
echo The GCD is: $n
