#!/bin/bash


echo "a"

arg_1="$1"
arg_2="$2"
 
if [ "$arg_1" -gt "$arg_2" ]
then
  echo "$arg_1 > $arg_2"
else
  echo "$arg_1 <= $arg_2"
fi


echo "b"

        for (( i=0; i < 2; i++ )); do
                if [[ $1 -lt $2 ]]; then
                        shift
                else
                        set $1 $3
                fi
        done
        echo $1
