#!/bin/bash

echo "Input first number:"
 
read a
 
echo "Input second number:"
 
read b
 
echo "Enter the number of sequence elements:"
 
read N
 
echo "Первые" $N "чисел Фибоначчи:"
 
i=0
 
while [ $i -le $N ]
 
do
 
let "d=(($b+$a))"
 
a=$b
 
b=$d
 
let "i+=1"
 
echo "$b"
 
done
