#!/bin/bash

vi vifile1

#нажми i для ввода текста
#написался,теперь нажми Esc а потом введи :
#:q! - выйти без сохранения;
#:wq - записать файл и выйти;
#ZZ - записать файл и выйти (Если файл не изменяли, то записываться он не будет)

vi vifile2

echo "first file"
cat vifile1

echo "second file"
cat vifile2
